apiVersion: v1
kind: ConfigMap
metadata:
  name: watch-config
  labels:
    app: watch-config
data:
  config.yaml: |
    prometheus:
      server: http://prometheus-server
      auth: None
    apis:
      metric-api:
        port: ':8080'
        timeout: 5000
    elasticsearch8:
      endpoint: http://elasticsearch:9200
      user:
      password:
    influxdb:
      endpoint: http://influxdb:8086
      database: sre_metrics
