{{/* 加载资源预设（传递type参数为.Values.resourcesPreset） */}}
{{- $preset := include "opspilot.resources.preset" (dict "type" .Values.cronjob.resourcesPreset) | fromYaml -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "watch.fullname" . }}-cronjob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 100
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: watch-cronjob
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: Always
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 2000
                runAsNonRoot: true
              env:
                - name: FUNCTION
                  value: cronjob
                - name: LOGLEVEL
                  value: info
                - name: SUC_THRESHOLD # slo-month
                  value: "99.9"
                - name: LAT_THRESHOLD # slo-month
                  value: "500"
                - name: REFRESH_NDAY # slo-month
                  value: "3"
                - name: TZ
                  value: Asia/Shanghai
              {{- if .Values.cronjob.resources }}
              resources:{{- toYaml .Values.cronjob.resources | nindent 16 }}
              {{- else if ne .Values.cronjob.resourcesPreset "none"}}
              resources:
                requests: {{ toYaml $preset.requests | nindent 18 }}
                limits: {{ toYaml $preset.limits | nindent 18 }}
              {{- end }}
              volumeMounts:
                - mountPath: /opt/config/config.yaml
                  name: config-volume
                  subPath: config.yaml
          volumes:
            - name: config-volume
              configMap:
                  name: watch-config
          restartPolicy: OnFailure
          activeDeadlineSeconds: 300