apiVersion: v1
kind: Service
metadata:
  name: {{ include "watch.fullname" . }}-service
  labels:
    {{- include "watch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    type: service
    {{- include "watch.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "watch.fullname" . }}-exporter
  labels:
    {{- include "watch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: watch-exporter
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: watch-exporter-grpc
  selector:
    type: exporter
    {{- include "watch.selectorLabels" . | nindent 4 }}