apiVersion: v1
kind: Secret
metadata:
  name: sql-advisory-mcp-access-key
  namespace: opspilot
data:
  SQL_ADVISORY_MCP_ACCESS_KEY: QW13YXlfa2V5XzEyMw==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-metrics-mcp-access-key
  namespace: opspilot
data:
  CMS_METRICS_MCP_ACCESS_KEY: QW13YXlfa2V5XzEyMw==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: watch-api-mcp-access-key
  namespace: opspilot
data:
  WATCH_API_MCP_ACCESS_KEY: QW13YXlfa2V5XzEyMw==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: service-config-mcp-access-key
  namespace: opspilot
data:
  SERVICE_CONFIG_MCP_ACCESS_KEY: QW13YXlfa2V5XzEyMw==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ali-slowlog-mcp-access-key
  namespace: opspilot
data:
  ALI_SLOWLOG_MCP_ACCESS_KEY: QW13YXlfa2V5XzEyMw==
type: Opaque