apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: aiops
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: PayBySpec
spec:
  selector:
    app: agent-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: cc-connect
      port: 1455
      targetPort: cc-connect
  type: LoadBalancer
