apiVersion: v1
kind: Secret
metadata:
  name: cc-connect-secret
  namespace: aiops
type: Opaque
data:
  FEISHU_APP_ID: Y2xpX2E5NDc2OTQ3OTIyNGRiZDg=
  FEISHU_APP_SECRET: TDRvYkdUYjNrWWVWUndxMkh3Y1d1Y1FZRm1EU2p4dWw=
