{{/* 加载资源预设（传递type参数为.Values.preset） */}}
{{- $preset := include "common.resources.preset" (dict "type" .Values.resourcesPreset) | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lookout.fullname" . }}-service
  labels:
    {{- include "lookout.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- else if ne .Values.resourcesPreset "none" }}
  replicas: {{ $preset.replicaCount }}
  {{- end }}
  {{- end}}
  selector:
    matchLabels:
      {{- include "lookout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lookout.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lookout.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "opspilot.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- else if ne .Values.resourcesPreset "none" }}
          resources:
            requests: {{ toYaml $preset.requests | nindent 12 }}
            limits: {{ toYaml $preset.limits | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /opt/configs/config.yaml
              name: config-volume
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: lookout-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
