apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-cc-connect-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  FEISHU_APP_ID: {{ .Values.ccConnect.credentials.feishuAppIdBase64 | quote }}
  FEISHU_APP_SECRET: {{ .Values.ccConnect.credentials.feishuAppSecretBase64 | quote }}
