apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: cc-connect
      port: {{ .Values.service.ports.ccConnect }}
      targetPort: cc-connect
      protocol: TCP
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
