apiVersion: v1
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2Ftd2F5LWRldm9wcy1yZWdpc3RyeS5jbi1zaGVuemhlbi5jci5hbGl5dW5jcy5jb20vdjIvIjp7InVzZXJuYW1lIjoiZGV2b3BzX3BkX3JlYWRvbmx5X2FwaUBBbXdheUFDQ0xQRCIsInBhc3N3b3JkIjoiR0dCSmhMS2ZSaEM0bldETkZ4WEwiLCJlbWFpbCI6IjYwMTIxMTE1MEBxcS5jb20iLCJhdXRoIjoiWkdWMmIzQnpYM0JrWDNKbFlXUnZibXg1WDJGd2FVQkJiWGRoZVVGRFEweFFSRHBIUjBKS2FFeExabEpvUXpSdVYwUk9SbmhZVEE9PSJ9fX0="
kind: Secret
metadata:
  name: alicloud-registry-secret
type: kubernetes.io/dockerconfigjson
